"""create chat and chat_message tables

Revision ID: b99e3491f5ce
Revises: c67381308a0b
Create Date: 2026-03-30 23:03:44.130052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

from movie_nerd.infrastructure.persistence.sql_alchemy.orm import IdentityType

# revision identifiers, used by Alembic.
revision: str = 'b99e3491f5ce'
down_revision: Union[str, Sequence[str], None] = 'c67381308a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', IdentityType(), nullable=False),
    sa.Column('user_id', IdentityType(), nullable=False),
    sa.Column('status', sa.Enum('STARTED', name='chat_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message',
    sa.Column('id', IdentityType(), nullable=False),
    sa.Column('chat_id', IdentityType(), nullable=False),
    sa.Column('sender', sa.Enum('USER', 'BOT', name='chat_message_sender'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message')
    op.drop_table('chat')
    bind = op.get_bind()
    ENUM('USER', 'BOT', name='chat_message_sender', create_type=False).drop(bind, checkfirst=True)
    ENUM('STARTED', name='chat_status', create_type=False).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
