"""create user table

Revision ID: c67381308a0b
Revises: 
Create Date: 2026-03-30 20:22:31.817155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from movie_nerd.infrastructure.persistence.sql_alchemy.orm import IdentityType

# revision identifiers, used by Alembic.
revision: str = 'c67381308a0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', IdentityType(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
